version: '1'

services:
  rvc:
    build:
      context: .
      dockerfile: Dockerfile.cuda118
    container_name: rvc
    ports:
      - 7865:7865
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]